# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from a2flow.content.v1 import content_pb2 as a2flow_dot_content_dot_v1_dot_content__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in a2flow/content/v1/content_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProject = channel.unary_unary(
                '/a2flow.content.v1.ContentService/CreateProject',
                request_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.Project.FromString,
                _registered_method=True)
        self.ListProjects = channel.unary_unary(
                '/a2flow.content.v1.ContentService/ListProjects',
                request_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.ListProjectsResponse.FromString,
                _registered_method=True)
        self.GetProject = channel.unary_unary(
                '/a2flow.content.v1.ContentService/GetProject',
                request_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.GetProjectRequest.SerializeToString,
                response_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.Project.FromString,
                _registered_method=True)
        self.SaveSource = channel.unary_unary(
                '/a2flow.content.v1.ContentService/SaveSource',
                request_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.SaveSourceRequest.SerializeToString,
                response_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.Source.FromString,
                _registered_method=True)
        self.GetSource = channel.unary_unary(
                '/a2flow.content.v1.ContentService/GetSource',
                request_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.GetSourceRequest.SerializeToString,
                response_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.Source.FromString,
                _registered_method=True)
        self.SaveArtifact = channel.unary_unary(
                '/a2flow.content.v1.ContentService/SaveArtifact',
                request_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.SaveArtifactRequest.SerializeToString,
                response_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.Artifact.FromString,
                _registered_method=True)
        self.GetArtifact = channel.unary_unary(
                '/a2flow.content.v1.ContentService/GetArtifact',
                request_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.GetArtifactRequest.SerializeToString,
                response_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.Artifact.FromString,
                _registered_method=True)
        self.ConfirmReading = channel.unary_unary(
                '/a2flow.content.v1.ContentService/ConfirmReading',
                request_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.ConfirmReadingRequest.SerializeToString,
                response_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.Confirmation.FromString,
                _registered_method=True)
        self.ConfirmTopic = channel.unary_unary(
                '/a2flow.content.v1.ContentService/ConfirmTopic',
                request_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.ConfirmTopicRequest.SerializeToString,
                response_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.Confirmation.FromString,
                _registered_method=True)
        self.ConfirmManuscript = channel.unary_unary(
                '/a2flow.content.v1.ContentService/ConfirmManuscript',
                request_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.ConfirmManuscriptRequest.SerializeToString,
                response_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.Confirmation.FromString,
                _registered_method=True)
        self.ExportManuscript = channel.unary_unary(
                '/a2flow.content.v1.ContentService/ExportManuscript',
                request_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.ExportManuscriptRequest.SerializeToString,
                response_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.ExportManuscriptResponse.FromString,
                _registered_method=True)


class ContentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmReading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmTopic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmManuscript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportManuscript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.CreateProjectRequest.FromString,
                    response_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.Project.SerializeToString,
            ),
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.ListProjectsRequest.FromString,
                    response_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.ListProjectsResponse.SerializeToString,
            ),
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.GetProjectRequest.FromString,
                    response_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.Project.SerializeToString,
            ),
            'SaveSource': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveSource,
                    request_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.SaveSourceRequest.FromString,
                    response_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.Source.SerializeToString,
            ),
            'GetSource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSource,
                    request_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.GetSourceRequest.FromString,
                    response_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.Source.SerializeToString,
            ),
            'SaveArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveArtifact,
                    request_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.SaveArtifactRequest.FromString,
                    response_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.Artifact.SerializeToString,
            ),
            'GetArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifact,
                    request_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.GetArtifactRequest.FromString,
                    response_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.Artifact.SerializeToString,
            ),
            'ConfirmReading': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmReading,
                    request_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.ConfirmReadingRequest.FromString,
                    response_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.Confirmation.SerializeToString,
            ),
            'ConfirmTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmTopic,
                    request_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.ConfirmTopicRequest.FromString,
                    response_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.Confirmation.SerializeToString,
            ),
            'ConfirmManuscript': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmManuscript,
                    request_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.ConfirmManuscriptRequest.FromString,
                    response_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.Confirmation.SerializeToString,
            ),
            'ExportManuscript': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportManuscript,
                    request_deserializer=a2flow_dot_content_dot_v1_dot_content__pb2.ExportManuscriptRequest.FromString,
                    response_serializer=a2flow_dot_content_dot_v1_dot_content__pb2.ExportManuscriptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2flow.content.v1.ContentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2flow.content.v1.ContentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.content.v1.ContentService/CreateProject',
            a2flow_dot_content_dot_v1_dot_content__pb2.CreateProjectRequest.SerializeToString,
            a2flow_dot_content_dot_v1_dot_content__pb2.Project.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.content.v1.ContentService/ListProjects',
            a2flow_dot_content_dot_v1_dot_content__pb2.ListProjectsRequest.SerializeToString,
            a2flow_dot_content_dot_v1_dot_content__pb2.ListProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.content.v1.ContentService/GetProject',
            a2flow_dot_content_dot_v1_dot_content__pb2.GetProjectRequest.SerializeToString,
            a2flow_dot_content_dot_v1_dot_content__pb2.Project.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.content.v1.ContentService/SaveSource',
            a2flow_dot_content_dot_v1_dot_content__pb2.SaveSourceRequest.SerializeToString,
            a2flow_dot_content_dot_v1_dot_content__pb2.Source.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.content.v1.ContentService/GetSource',
            a2flow_dot_content_dot_v1_dot_content__pb2.GetSourceRequest.SerializeToString,
            a2flow_dot_content_dot_v1_dot_content__pb2.Source.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.content.v1.ContentService/SaveArtifact',
            a2flow_dot_content_dot_v1_dot_content__pb2.SaveArtifactRequest.SerializeToString,
            a2flow_dot_content_dot_v1_dot_content__pb2.Artifact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.content.v1.ContentService/GetArtifact',
            a2flow_dot_content_dot_v1_dot_content__pb2.GetArtifactRequest.SerializeToString,
            a2flow_dot_content_dot_v1_dot_content__pb2.Artifact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmReading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.content.v1.ContentService/ConfirmReading',
            a2flow_dot_content_dot_v1_dot_content__pb2.ConfirmReadingRequest.SerializeToString,
            a2flow_dot_content_dot_v1_dot_content__pb2.Confirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.content.v1.ContentService/ConfirmTopic',
            a2flow_dot_content_dot_v1_dot_content__pb2.ConfirmTopicRequest.SerializeToString,
            a2flow_dot_content_dot_v1_dot_content__pb2.Confirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmManuscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.content.v1.ContentService/ConfirmManuscript',
            a2flow_dot_content_dot_v1_dot_content__pb2.ConfirmManuscriptRequest.SerializeToString,
            a2flow_dot_content_dot_v1_dot_content__pb2.Confirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportManuscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.content.v1.ContentService/ExportManuscript',
            a2flow_dot_content_dot_v1_dot_content__pb2.ExportManuscriptRequest.SerializeToString,
            a2flow_dot_content_dot_v1_dot_content__pb2.ExportManuscriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
