"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import a2flow.content.v1.content_pb2
import abc
import collections.abc
import grpc
import grpc.aio
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_ContentServiceCreateProjectType = typing_extensions.TypeVar(
    '_ContentServiceCreateProjectType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.CreateProjectRequest,
        a2flow.content.v1.content_pb2.Project,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.CreateProjectRequest,
        a2flow.content.v1.content_pb2.Project,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.CreateProjectRequest,
        a2flow.content.v1.content_pb2.Project,
    ],
)

_ContentServiceListProjectsType = typing_extensions.TypeVar(
    '_ContentServiceListProjectsType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ListProjectsRequest,
        a2flow.content.v1.content_pb2.ListProjectsResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ListProjectsRequest,
        a2flow.content.v1.content_pb2.ListProjectsResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ListProjectsRequest,
        a2flow.content.v1.content_pb2.ListProjectsResponse,
    ],
)

_ContentServiceListPeopleType = typing_extensions.TypeVar(
    '_ContentServiceListPeopleType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ListPeopleRequest,
        a2flow.content.v1.content_pb2.ListPeopleResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ListPeopleRequest,
        a2flow.content.v1.content_pb2.ListPeopleResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ListPeopleRequest,
        a2flow.content.v1.content_pb2.ListPeopleResponse,
    ],
)

_ContentServiceResolvePeopleType = typing_extensions.TypeVar(
    '_ContentServiceResolvePeopleType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ResolvePeopleRequest,
        a2flow.content.v1.content_pb2.ResolvePeopleResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ResolvePeopleRequest,
        a2flow.content.v1.content_pb2.ResolvePeopleResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ResolvePeopleRequest,
        a2flow.content.v1.content_pb2.ResolvePeopleResponse,
    ],
)

_ContentServiceGetProjectType = typing_extensions.TypeVar(
    '_ContentServiceGetProjectType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetProjectRequest,
        a2flow.content.v1.content_pb2.Project,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetProjectRequest,
        a2flow.content.v1.content_pb2.Project,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetProjectRequest,
        a2flow.content.v1.content_pb2.Project,
    ],
)

_ContentServiceSaveSourceType = typing_extensions.TypeVar(
    '_ContentServiceSaveSourceType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.SaveSourceRequest,
        a2flow.content.v1.content_pb2.Source,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.SaveSourceRequest,
        a2flow.content.v1.content_pb2.Source,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.SaveSourceRequest,
        a2flow.content.v1.content_pb2.Source,
    ],
)

_ContentServiceGetSourceType = typing_extensions.TypeVar(
    '_ContentServiceGetSourceType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetSourceRequest,
        a2flow.content.v1.content_pb2.Source,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetSourceRequest,
        a2flow.content.v1.content_pb2.Source,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetSourceRequest,
        a2flow.content.v1.content_pb2.Source,
    ],
)

_ContentServiceSaveArtifactType = typing_extensions.TypeVar(
    '_ContentServiceSaveArtifactType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.SaveArtifactRequest,
        a2flow.content.v1.content_pb2.Artifact,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.SaveArtifactRequest,
        a2flow.content.v1.content_pb2.Artifact,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.SaveArtifactRequest,
        a2flow.content.v1.content_pb2.Artifact,
    ],
)

_ContentServiceGetArtifactType = typing_extensions.TypeVar(
    '_ContentServiceGetArtifactType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetArtifactRequest,
        a2flow.content.v1.content_pb2.Artifact,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetArtifactRequest,
        a2flow.content.v1.content_pb2.Artifact,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetArtifactRequest,
        a2flow.content.v1.content_pb2.Artifact,
    ],
)

_ContentServiceGetConfirmationType = typing_extensions.TypeVar(
    '_ContentServiceGetConfirmationType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetConfirmationRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetConfirmationRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetConfirmationRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
)

_ContentServiceConfirmReadingType = typing_extensions.TypeVar(
    '_ContentServiceConfirmReadingType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmReadingRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmReadingRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmReadingRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
)

_ContentServiceConfirmTopicType = typing_extensions.TypeVar(
    '_ContentServiceConfirmTopicType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmTopicRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmTopicRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmTopicRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
)

_ContentServiceConfirmManuscriptType = typing_extensions.TypeVar(
    '_ContentServiceConfirmManuscriptType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmManuscriptRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmManuscriptRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmManuscriptRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
)

_ContentServiceExportManuscriptType = typing_extensions.TypeVar(
    '_ContentServiceExportManuscriptType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ExportManuscriptRequest,
        a2flow.content.v1.content_pb2.ExportManuscriptResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ExportManuscriptRequest,
        a2flow.content.v1.content_pb2.ExportManuscriptResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ExportManuscriptRequest,
        a2flow.content.v1.content_pb2.ExportManuscriptResponse,
    ],
)

class ContentServiceStub(typing.Generic[_ContentServiceCreateProjectType, _ContentServiceListProjectsType, _ContentServiceListPeopleType, _ContentServiceResolvePeopleType, _ContentServiceGetProjectType, _ContentServiceSaveSourceType, _ContentServiceGetSourceType, _ContentServiceSaveArtifactType, _ContentServiceGetArtifactType, _ContentServiceGetConfirmationType, _ContentServiceConfirmReadingType, _ContentServiceConfirmTopicType, _ContentServiceConfirmManuscriptType, _ContentServiceExportManuscriptType]):
    @typing.overload
    def __init__(self: ContentServiceStub[
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.CreateProjectRequest,
            a2flow.content.v1.content_pb2.Project,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ListProjectsRequest,
            a2flow.content.v1.content_pb2.ListProjectsResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ListPeopleRequest,
            a2flow.content.v1.content_pb2.ListPeopleResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ResolvePeopleRequest,
            a2flow.content.v1.content_pb2.ResolvePeopleResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.GetProjectRequest,
            a2flow.content.v1.content_pb2.Project,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.SaveSourceRequest,
            a2flow.content.v1.content_pb2.Source,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.GetSourceRequest,
            a2flow.content.v1.content_pb2.Source,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.SaveArtifactRequest,
            a2flow.content.v1.content_pb2.Artifact,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.GetArtifactRequest,
            a2flow.content.v1.content_pb2.Artifact,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.GetConfirmationRequest,
            a2flow.content.v1.content_pb2.Confirmation,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ConfirmReadingRequest,
            a2flow.content.v1.content_pb2.Confirmation,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ConfirmTopicRequest,
            a2flow.content.v1.content_pb2.Confirmation,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ConfirmManuscriptRequest,
            a2flow.content.v1.content_pb2.Confirmation,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ExportManuscriptRequest,
            a2flow.content.v1.content_pb2.ExportManuscriptResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: ContentServiceStub[
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.CreateProjectRequest,
            a2flow.content.v1.content_pb2.Project,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ListProjectsRequest,
            a2flow.content.v1.content_pb2.ListProjectsResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ListPeopleRequest,
            a2flow.content.v1.content_pb2.ListPeopleResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ResolvePeopleRequest,
            a2flow.content.v1.content_pb2.ResolvePeopleResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.GetProjectRequest,
            a2flow.content.v1.content_pb2.Project,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.SaveSourceRequest,
            a2flow.content.v1.content_pb2.Source,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.GetSourceRequest,
            a2flow.content.v1.content_pb2.Source,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.SaveArtifactRequest,
            a2flow.content.v1.content_pb2.Artifact,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.GetArtifactRequest,
            a2flow.content.v1.content_pb2.Artifact,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.GetConfirmationRequest,
            a2flow.content.v1.content_pb2.Confirmation,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ConfirmReadingRequest,
            a2flow.content.v1.content_pb2.Confirmation,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ConfirmTopicRequest,
            a2flow.content.v1.content_pb2.Confirmation,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ConfirmManuscriptRequest,
            a2flow.content.v1.content_pb2.Confirmation,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.content.v1.content_pb2.ExportManuscriptRequest,
            a2flow.content.v1.content_pb2.ExportManuscriptResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    CreateProject: _ContentServiceCreateProjectType

    ListProjects: _ContentServiceListProjectsType

    ListPeople: _ContentServiceListPeopleType

    ResolvePeople: _ContentServiceResolvePeopleType

    GetProject: _ContentServiceGetProjectType

    SaveSource: _ContentServiceSaveSourceType

    GetSource: _ContentServiceGetSourceType

    SaveArtifact: _ContentServiceSaveArtifactType

    GetArtifact: _ContentServiceGetArtifactType

    GetConfirmation: _ContentServiceGetConfirmationType

    ConfirmReading: _ContentServiceConfirmReadingType

    ConfirmTopic: _ContentServiceConfirmTopicType

    ConfirmManuscript: _ContentServiceConfirmManuscriptType

    ExportManuscript: _ContentServiceExportManuscriptType

ContentServiceAsyncStub: typing_extensions.TypeAlias = ContentServiceStub[
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.CreateProjectRequest,
        a2flow.content.v1.content_pb2.Project,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ListProjectsRequest,
        a2flow.content.v1.content_pb2.ListProjectsResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ListPeopleRequest,
        a2flow.content.v1.content_pb2.ListPeopleResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ResolvePeopleRequest,
        a2flow.content.v1.content_pb2.ResolvePeopleResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetProjectRequest,
        a2flow.content.v1.content_pb2.Project,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.SaveSourceRequest,
        a2flow.content.v1.content_pb2.Source,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetSourceRequest,
        a2flow.content.v1.content_pb2.Source,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.SaveArtifactRequest,
        a2flow.content.v1.content_pb2.Artifact,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetArtifactRequest,
        a2flow.content.v1.content_pb2.Artifact,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.GetConfirmationRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmReadingRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmTopicRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ConfirmManuscriptRequest,
        a2flow.content.v1.content_pb2.Confirmation,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.content.v1.content_pb2.ExportManuscriptRequest,
        a2flow.content.v1.content_pb2.ExportManuscriptResponse,
    ],
]

class ContentServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def CreateProject(
        self,
        request: a2flow.content.v1.content_pb2.CreateProjectRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.Project, collections.abc.Awaitable[a2flow.content.v1.content_pb2.Project]]: ...

    @abc.abstractmethod
    def ListProjects(
        self,
        request: a2flow.content.v1.content_pb2.ListProjectsRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.ListProjectsResponse, collections.abc.Awaitable[a2flow.content.v1.content_pb2.ListProjectsResponse]]: ...

    @abc.abstractmethod
    def ListPeople(
        self,
        request: a2flow.content.v1.content_pb2.ListPeopleRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.ListPeopleResponse, collections.abc.Awaitable[a2flow.content.v1.content_pb2.ListPeopleResponse]]: ...

    @abc.abstractmethod
    def ResolvePeople(
        self,
        request: a2flow.content.v1.content_pb2.ResolvePeopleRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.ResolvePeopleResponse, collections.abc.Awaitable[a2flow.content.v1.content_pb2.ResolvePeopleResponse]]: ...

    @abc.abstractmethod
    def GetProject(
        self,
        request: a2flow.content.v1.content_pb2.GetProjectRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.Project, collections.abc.Awaitable[a2flow.content.v1.content_pb2.Project]]: ...

    @abc.abstractmethod
    def SaveSource(
        self,
        request: a2flow.content.v1.content_pb2.SaveSourceRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.Source, collections.abc.Awaitable[a2flow.content.v1.content_pb2.Source]]: ...

    @abc.abstractmethod
    def GetSource(
        self,
        request: a2flow.content.v1.content_pb2.GetSourceRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.Source, collections.abc.Awaitable[a2flow.content.v1.content_pb2.Source]]: ...

    @abc.abstractmethod
    def SaveArtifact(
        self,
        request: a2flow.content.v1.content_pb2.SaveArtifactRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.Artifact, collections.abc.Awaitable[a2flow.content.v1.content_pb2.Artifact]]: ...

    @abc.abstractmethod
    def GetArtifact(
        self,
        request: a2flow.content.v1.content_pb2.GetArtifactRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.Artifact, collections.abc.Awaitable[a2flow.content.v1.content_pb2.Artifact]]: ...

    @abc.abstractmethod
    def GetConfirmation(
        self,
        request: a2flow.content.v1.content_pb2.GetConfirmationRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.Confirmation, collections.abc.Awaitable[a2flow.content.v1.content_pb2.Confirmation]]: ...

    @abc.abstractmethod
    def ConfirmReading(
        self,
        request: a2flow.content.v1.content_pb2.ConfirmReadingRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.Confirmation, collections.abc.Awaitable[a2flow.content.v1.content_pb2.Confirmation]]: ...

    @abc.abstractmethod
    def ConfirmTopic(
        self,
        request: a2flow.content.v1.content_pb2.ConfirmTopicRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.Confirmation, collections.abc.Awaitable[a2flow.content.v1.content_pb2.Confirmation]]: ...

    @abc.abstractmethod
    def ConfirmManuscript(
        self,
        request: a2flow.content.v1.content_pb2.ConfirmManuscriptRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.Confirmation, collections.abc.Awaitable[a2flow.content.v1.content_pb2.Confirmation]]: ...

    @abc.abstractmethod
    def ExportManuscript(
        self,
        request: a2flow.content.v1.content_pb2.ExportManuscriptRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.content.v1.content_pb2.ExportManuscriptResponse, collections.abc.Awaitable[a2flow.content.v1.content_pb2.ExportManuscriptResponse]]: ...

def add_ContentServiceServicer_to_server(servicer: ContentServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
