"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import a2flow.capability.v1.capability_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Project(google.protobuf.message.Message):
    """Identity is supplied by the authenticated execution service, never by model arguments.
    This service owns business data, not Agent history or Workflow execution state.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    AUDIENCE_FIELD_NUMBER: builtins.int
    OUTPUT_FORMAT_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    CURRENT_SELECTION_ID_FIELD_NUMBER: builtins.int
    CURRENT_MANUSCRIPT_ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    CURRENT_SOURCE_ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    title: builtins.str
    audience: builtins.str
    output_format: builtins.str
    revision: builtins.int
    current_selection_id: builtins.str
    current_manuscript_id: builtins.str
    created_at: builtins.str
    updated_at: builtins.str
    current_source_id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        title: builtins.str = ...,
        audience: builtins.str = ...,
        output_format: builtins.str = ...,
        revision: builtins.int = ...,
        current_selection_id: builtins.str = ...,
        current_manuscript_id: builtins.str = ...,
        created_at: builtins.str = ...,
        updated_at: builtins.str = ...,
        current_source_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["audience", b"audience", "created_at", b"created_at", "current_manuscript_id", b"current_manuscript_id", "current_selection_id", b"current_selection_id", "current_source_id", b"current_source_id", "id", b"id", "output_format", b"output_format", "revision", b"revision", "title", b"title", "updated_at", b"updated_at"]) -> None: ...

Global___Project: typing_extensions.TypeAlias = Project

@typing.final
class Source(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    SOURCE_URL_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    DIGEST_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    project_id: builtins.str
    revision: builtins.int
    title: builtins.str
    source_url: builtins.str
    body: builtins.str
    digest: builtins.str
    created_at: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        project_id: builtins.str = ...,
        revision: builtins.int = ...,
        title: builtins.str = ...,
        source_url: builtins.str = ...,
        body: builtins.str = ...,
        digest: builtins.str = ...,
        created_at: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["body", b"body", "created_at", b"created_at", "digest", b"digest", "id", b"id", "project_id", b"project_id", "revision", b"revision", "source_url", b"source_url", "title", b"title"]) -> None: ...

Global___Source: typing_extensions.TypeAlias = Source

@typing.final
class InputReference(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KIND_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    kind: builtins.str
    id: builtins.str
    revision: builtins.int
    def __init__(
        self,
        *,
        kind: builtins.str = ...,
        id: builtins.str = ...,
        revision: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "kind", b"kind", "revision", b"revision"]) -> None: ...

Global___InputReference: typing_extensions.TypeAlias = InputReference

@typing.final
class ReadingPoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CLAIM_FIELD_NUMBER: builtins.int
    EVIDENCE_QUOTE_FIELD_NUMBER: builtins.int
    EVIDENCE_LOCATOR_FIELD_NUMBER: builtins.int
    EXPLANATION_FIELD_NUMBER: builtins.int
    MODEL_SUGGESTION_FIELD_NUMBER: builtins.int
    id: builtins.str
    claim: builtins.str
    evidence_quote: builtins.str
    evidence_locator: builtins.str
    explanation: builtins.str
    model_suggestion: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        claim: builtins.str = ...,
        evidence_quote: builtins.str | None = ...,
        evidence_locator: builtins.str | None = ...,
        explanation: builtins.str = ...,
        model_suggestion: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_evidence_locator", b"_evidence_locator", "_evidence_quote", b"_evidence_quote", "evidence_locator", b"evidence_locator", "evidence_quote", b"evidence_quote"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_evidence_locator", b"_evidence_locator", "_evidence_quote", b"_evidence_quote", "claim", b"claim", "evidence_locator", b"evidence_locator", "evidence_quote", b"evidence_quote", "explanation", b"explanation", "id", b"id", "model_suggestion", b"model_suggestion"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_evidence_locator", b"_evidence_locator"]) -> typing.Literal["evidence_locator"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_evidence_quote", b"_evidence_quote"]) -> typing.Literal["evidence_quote"] | None: ...

Global___ReadingPoint: typing_extensions.TypeAlias = ReadingPoint

@typing.final
class ReadingBrief(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POINTS_FIELD_NUMBER: builtins.int
    QUESTIONS_FIELD_NUMBER: builtins.int
    USABLE_MATERIALS_FIELD_NUMBER: builtins.int
    @property
    def points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ReadingPoint]: ...
    @property
    def questions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def usable_materials(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        points: collections.abc.Iterable[Global___ReadingPoint] | None = ...,
        questions: collections.abc.Iterable[builtins.str] | None = ...,
        usable_materials: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["points", b"points", "questions", b"questions", "usable_materials", b"usable_materials"]) -> None: ...

Global___ReadingBrief: typing_extensions.TypeAlias = ReadingBrief

@typing.final
class TopicOption(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    ANGLE_FIELD_NUMBER: builtins.int
    AUDIENCE_FIELD_NUMBER: builtins.int
    RATIONALE_FIELD_NUMBER: builtins.int
    SOURCE_POINT_IDS_FIELD_NUMBER: builtins.int
    id: builtins.str
    title: builtins.str
    angle: builtins.str
    audience: builtins.str
    rationale: builtins.str
    @property
    def source_point_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        title: builtins.str = ...,
        angle: builtins.str = ...,
        audience: builtins.str = ...,
        rationale: builtins.str = ...,
        source_point_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["angle", b"angle", "audience", b"audience", "id", b"id", "rationale", b"rationale", "source_point_ids", b"source_point_ids", "title", b"title"]) -> None: ...

Global___TopicOption: typing_extensions.TypeAlias = TopicOption

@typing.final
class TopicPlan(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOPICS_FIELD_NUMBER: builtins.int
    @property
    def topics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TopicOption]: ...
    def __init__(
        self,
        *,
        topics: collections.abc.Iterable[Global___TopicOption] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["topics", b"topics"]) -> None: ...

Global___TopicPlan: typing_extensions.TypeAlias = TopicPlan

@typing.final
class Citation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REFERENCE_KIND_FIELD_NUMBER: builtins.int
    REFERENCE_ID_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    reference_kind: builtins.str
    reference_id: builtins.str
    revision: builtins.int
    label: builtins.str
    def __init__(
        self,
        *,
        reference_kind: builtins.str = ...,
        reference_id: builtins.str = ...,
        revision: builtins.int = ...,
        label: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["label", b"label", "reference_id", b"reference_id", "reference_kind", b"reference_kind", "revision", b"revision"]) -> None: ...

Global___Citation: typing_extensions.TypeAlias = Citation

@typing.final
class Manuscript(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TITLE_FIELD_NUMBER: builtins.int
    BODY_MARKDOWN_FIELD_NUMBER: builtins.int
    CITATIONS_FIELD_NUMBER: builtins.int
    title: builtins.str
    body_markdown: builtins.str
    @property
    def citations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Citation]: ...
    def __init__(
        self,
        *,
        title: builtins.str = ...,
        body_markdown: builtins.str = ...,
        citations: collections.abc.Iterable[Global___Citation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["body_markdown", b"body_markdown", "citations", b"citations", "title", b"title"]) -> None: ...

Global___Manuscript: typing_extensions.TypeAlias = Manuscript

@typing.final
class ArtifactBody(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    READING_BRIEF_FIELD_NUMBER: builtins.int
    TOPIC_PLAN_FIELD_NUMBER: builtins.int
    MANUSCRIPT_FIELD_NUMBER: builtins.int
    @property
    def reading_brief(self) -> Global___ReadingBrief: ...
    @property
    def topic_plan(self) -> Global___TopicPlan: ...
    @property
    def manuscript(self) -> Global___Manuscript: ...
    def __init__(
        self,
        *,
        reading_brief: Global___ReadingBrief | None = ...,
        topic_plan: Global___TopicPlan | None = ...,
        manuscript: Global___Manuscript | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["manuscript", b"manuscript", "reading_brief", b"reading_brief", "topic_plan", b"topic_plan", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["manuscript", b"manuscript", "reading_brief", b"reading_brief", "topic_plan", b"topic_plan", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value", b"value"]) -> typing.Literal["reading_brief", "topic_plan", "manuscript"] | None: ...

Global___ArtifactBody: typing_extensions.TypeAlias = ArtifactBody

@typing.final
class Artifact(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    BODY_MARKDOWN_FIELD_NUMBER: builtins.int
    INPUT_REFS_FIELD_NUMBER: builtins.int
    ORIGIN_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    project_id: builtins.str
    kind: builtins.str
    revision: builtins.int
    body_markdown: builtins.str
    origin: builtins.str
    created_at: builtins.str
    @property
    def body(self) -> Global___ArtifactBody: ...
    @property
    def input_refs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___InputReference]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        project_id: builtins.str = ...,
        kind: builtins.str = ...,
        revision: builtins.int = ...,
        body: Global___ArtifactBody | None = ...,
        body_markdown: builtins.str = ...,
        input_refs: collections.abc.Iterable[Global___InputReference] | None = ...,
        origin: builtins.str = ...,
        created_at: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["body", b"body"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["body", b"body", "body_markdown", b"body_markdown", "created_at", b"created_at", "id", b"id", "input_refs", b"input_refs", "kind", b"kind", "origin", b"origin", "project_id", b"project_id", "revision", b"revision"]) -> None: ...

Global___Artifact: typing_extensions.TypeAlias = Artifact

@typing.final
class Confirmation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    ARTIFACT_ID_FIELD_NUMBER: builtins.int
    DECISION_TYPE_FIELD_NUMBER: builtins.int
    SELECTED_POINT_IDS_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    USER_NOTES_FIELD_NUMBER: builtins.int
    TOPIC_ID_FIELD_NUMBER: builtins.int
    EDITED_TITLE_FIELD_NUMBER: builtins.int
    EDITED_ANGLE_FIELD_NUMBER: builtins.int
    id: builtins.str
    project_id: builtins.str
    artifact_id: builtins.str
    decision_type: builtins.str
    created_at: builtins.str
    user_notes: builtins.str
    topic_id: builtins.str
    edited_title: builtins.str
    edited_angle: builtins.str
    @property
    def selected_point_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        project_id: builtins.str = ...,
        artifact_id: builtins.str = ...,
        decision_type: builtins.str = ...,
        selected_point_ids: collections.abc.Iterable[builtins.str] | None = ...,
        created_at: builtins.str = ...,
        user_notes: builtins.str = ...,
        topic_id: builtins.str = ...,
        edited_title: builtins.str = ...,
        edited_angle: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["artifact_id", b"artifact_id", "created_at", b"created_at", "decision_type", b"decision_type", "edited_angle", b"edited_angle", "edited_title", b"edited_title", "id", b"id", "project_id", b"project_id", "selected_point_ids", b"selected_point_ids", "topic_id", b"topic_id", "user_notes", b"user_notes"]) -> None: ...

Global___Confirmation: typing_extensions.TypeAlias = Confirmation

@typing.final
class CreateProjectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    AUDIENCE_FIELD_NUMBER: builtins.int
    OUTPUT_FORMAT_FIELD_NUMBER: builtins.int
    title: builtins.str
    audience: builtins.str
    output_format: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        title: builtins.str = ...,
        audience: builtins.str = ...,
        output_format: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["audience", b"audience", "context", b"context", "output_format", b"output_format", "title", b"title"]) -> None: ...

Global___CreateProjectRequest: typing_extensions.TypeAlias = CreateProjectRequest

@typing.final
class ListProjectsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    page: builtins.int
    page_size: builtins.int
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "page", b"page", "page_size", b"page_size"]) -> None: ...

Global___ListProjectsRequest: typing_extensions.TypeAlias = ListProjectsRequest

@typing.final
class ListProjectsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIST_FIELD_NUMBER: builtins.int
    TOTAL_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    total: builtins.int
    page: builtins.int
    page_size: builtins.int
    @property
    def list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Project]: ...
    def __init__(
        self,
        *,
        list: collections.abc.Iterable[Global___Project] | None = ...,
        total: builtins.int = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["list", b"list", "page", b"page", "page_size", b"page_size", "total", b"total"]) -> None: ...

Global___ListProjectsResponse: typing_extensions.TypeAlias = ListProjectsResponse

@typing.final
class GetProjectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    project_id: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        project_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "project_id", b"project_id"]) -> None: ...

Global___GetProjectRequest: typing_extensions.TypeAlias = GetProjectRequest

@typing.final
class SaveSourceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    SOURCE_URL_FIELD_NUMBER: builtins.int
    project_id: builtins.str
    title: builtins.str
    body: builtins.str
    source_url: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        project_id: builtins.str = ...,
        title: builtins.str = ...,
        body: builtins.str = ...,
        source_url: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["body", b"body", "context", b"context", "project_id", b"project_id", "source_url", b"source_url", "title", b"title"]) -> None: ...

Global___SaveSourceRequest: typing_extensions.TypeAlias = SaveSourceRequest

@typing.final
class GetSourceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    SOURCE_ID_FIELD_NUMBER: builtins.int
    source_id: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        source_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "source_id", b"source_id"]) -> None: ...

Global___GetSourceRequest: typing_extensions.TypeAlias = GetSourceRequest

@typing.final
class SaveArtifactRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    INPUT_REFS_FIELD_NUMBER: builtins.int
    ORIGIN_FIELD_NUMBER: builtins.int
    project_id: builtins.str
    kind: builtins.str
    origin: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    @property
    def body(self) -> Global___ArtifactBody: ...
    @property
    def input_refs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___InputReference]: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        project_id: builtins.str = ...,
        kind: builtins.str = ...,
        body: Global___ArtifactBody | None = ...,
        input_refs: collections.abc.Iterable[Global___InputReference] | None = ...,
        origin: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["body", b"body", "context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["body", b"body", "context", b"context", "input_refs", b"input_refs", "kind", b"kind", "origin", b"origin", "project_id", b"project_id"]) -> None: ...

Global___SaveArtifactRequest: typing_extensions.TypeAlias = SaveArtifactRequest

@typing.final
class GetArtifactRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    ARTIFACT_ID_FIELD_NUMBER: builtins.int
    artifact_id: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        artifact_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["artifact_id", b"artifact_id", "context", b"context"]) -> None: ...

Global___GetArtifactRequest: typing_extensions.TypeAlias = GetArtifactRequest

@typing.final
class GetConfirmationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    CONFIRMATION_ID_FIELD_NUMBER: builtins.int
    confirmation_id: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        confirmation_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["confirmation_id", b"confirmation_id", "context", b"context"]) -> None: ...

Global___GetConfirmationRequest: typing_extensions.TypeAlias = GetConfirmationRequest

@typing.final
class ConfirmReadingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    ARTIFACT_ID_FIELD_NUMBER: builtins.int
    SELECTED_POINT_IDS_FIELD_NUMBER: builtins.int
    USER_NOTES_FIELD_NUMBER: builtins.int
    project_id: builtins.str
    artifact_id: builtins.str
    user_notes: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    @property
    def selected_point_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        project_id: builtins.str = ...,
        artifact_id: builtins.str = ...,
        selected_point_ids: collections.abc.Iterable[builtins.str] | None = ...,
        user_notes: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["artifact_id", b"artifact_id", "context", b"context", "project_id", b"project_id", "selected_point_ids", b"selected_point_ids", "user_notes", b"user_notes"]) -> None: ...

Global___ConfirmReadingRequest: typing_extensions.TypeAlias = ConfirmReadingRequest

@typing.final
class ConfirmTopicRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    ARTIFACT_ID_FIELD_NUMBER: builtins.int
    TOPIC_ID_FIELD_NUMBER: builtins.int
    EDITED_TITLE_FIELD_NUMBER: builtins.int
    EDITED_ANGLE_FIELD_NUMBER: builtins.int
    project_id: builtins.str
    artifact_id: builtins.str
    topic_id: builtins.str
    edited_title: builtins.str
    edited_angle: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        project_id: builtins.str = ...,
        artifact_id: builtins.str = ...,
        topic_id: builtins.str = ...,
        edited_title: builtins.str = ...,
        edited_angle: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["artifact_id", b"artifact_id", "context", b"context", "edited_angle", b"edited_angle", "edited_title", b"edited_title", "project_id", b"project_id", "topic_id", b"topic_id"]) -> None: ...

Global___ConfirmTopicRequest: typing_extensions.TypeAlias = ConfirmTopicRequest

@typing.final
class ConfirmManuscriptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    ARTIFACT_ID_FIELD_NUMBER: builtins.int
    project_id: builtins.str
    artifact_id: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        project_id: builtins.str = ...,
        artifact_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["artifact_id", b"artifact_id", "context", b"context", "project_id", b"project_id"]) -> None: ...

Global___ConfirmManuscriptRequest: typing_extensions.TypeAlias = ConfirmManuscriptRequest

@typing.final
class ExportManuscriptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    ARTIFACT_ID_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    artifact_id: builtins.str
    format: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        artifact_id: builtins.str = ...,
        format: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["artifact_id", b"artifact_id", "context", b"context", "format", b"format"]) -> None: ...

Global___ExportManuscriptRequest: typing_extensions.TypeAlias = ExportManuscriptRequest

@typing.final
class ExportManuscriptResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILENAME_FIELD_NUMBER: builtins.int
    MEDIA_TYPE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    filename: builtins.str
    media_type: builtins.str
    content: builtins.str
    def __init__(
        self,
        *,
        filename: builtins.str = ...,
        media_type: builtins.str = ...,
        content: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "filename", b"filename", "media_type", b"media_type"]) -> None: ...

Global___ExportManuscriptResponse: typing_extensions.TypeAlias = ExportManuscriptResponse
