package dev.a2flow.management.method;

import java.util.Arrays;
import java.util.Optional;

/**
 * SkillFactory 统一 method 枚举。
 *
 * <p>该枚举是 sellerdata SkillFactory 统一 RPC 的方法白名单。入口把上游传入的用户身份与
 * method/params 传给 dispatcher 后，仍须由领域服务执行资产权限和业务参数校验，避免任意字符串
 * 路由到工作区、发布或 Workflow 控制面能力。
 */
public enum SkillFactoryMethodEnum {

    SKILL_FACTORY_CONFIG,
    ASSET_ACCESS_GET,
    ASSET_OWNER_REPLACE,
    WORKFLOW_CREATE,
    WORKFLOW_DETAIL,
    WORKFLOW_LIST,
    WORKFLOW_BASIC_INFO_UPDATE,
    WORKFLOW_DRAFT_DETAIL,
    WORKFLOW_DRAFT_UPDATE,
    WORKFLOW_SKILL_CANDIDATES,
    WORKFLOW_COMPILED_PLAN_PREVIEW,
    SKILL_LIST,
    SKILL_DETAIL,
    SKILL_METADATA_BATCH_QUERY,
    SKILL_UPDATE,
    SKILL_COMPONENT_CANDIDATE_LIST,
    SKILL_CAPABILITY_CANDIDATE_LIST,
    ZIP_CONFIRM_IMPORT,
    WORKSPACE_CREATE,
    WORKSPACE_TREE,
    WORKSPACE_FILE_CONTENT,
    WORKSPACE_ZIP_EXPORT,
    WORKSPACE_FILE_SAVE,
    WORKSPACE_PATH_DELETE,
    WORKSPACE_RESET_FROM_VERSION,
    WORKSPACE_DIFF,
    WORKSPACE_SAVE,
    WORKSPACE_RENDER_SAMPLE_EXTRACT,
    SKILL_BINDINGS_REPLACE,
    RUNTIME_VALIDATE,
    PACKAGE_BUILD,
    PACKAGE_RELEASE_OPTIONS,
    PACKAGE_ONLINE_PUBLISH_DIFF,
    PACKAGE_PUBLISH_PREPROD,
    PACKAGE_PUBLISH_ONLINE,
    PACKAGE_VERSION_RESTORE,
    COMPONENT_LIST,
    COMPONENT_ENABLED_LIST,
    COMPONENT_PUBLISHED_LIST,
    COMPONENT_DETAIL,
    COMPONENT_REGISTER,
    COMPONENT_BASIC_INFO_UPDATE,
    COMPONENT_UPDATE,
    COMPONENT_OFFLINE,
    COMPONENT_PREVIEW,
    COMPONENT_RUNTIME_DETAIL,
    COMPONENT_RUNTIME_BATCH_GET,
    COMPONENT_RENDER_PREVIEW,
    A2UI_CATALOG_LIST,
    A2UI_CATALOG_DETAIL,
    A2UI_CATALOG_CREATE,
    A2UI_CATALOG_UPDATE,
    A2UI_CATALOG_MANAGED_IMPORT,
    A2UI_CATALOG_COMPONENT_LIST,
    A2UI_CATALOG_COMPONENT_DETAIL,
    A2UI_CATALOG_COMPONENT_CREATE,
    A2UI_CATALOG_COMPONENT_UPDATE,
    A2UI_APPLICATION_LIST,
    A2UI_APPLICATION_DETAIL,
    A2UI_APPLICATION_CREATE,
    A2UI_APPLICATION_UPDATE,
    A2UI_APPLICATION_BLUEPRINT_LIST,
    A2UI_APPLICATION_BLUEPRINT_IMPORT,
    A2UI_APPLICATION_ACTION_SCAN,
    CAPABILITY_LIST,
    CAPABILITY_PUBLISHED_LIST,
    CAPABILITY_DRAFT_CREATE,
    CAPABILITY_DRAFT_DETAIL,
    CAPABILITY_SKILL_CREATOR_CONTEXT,
    CAPABILITY_DRAFT_SAVE,
    CAPABILITY_VALIDATE,
    CAPABILITY_DRY_RUN,
    CAPABILITY_PUBLISH,
    RELEASE_OVERVIEW,
    RELEASE_CHANGE_CREATE,
    RELEASE_DIFF,
    RELEASE_PREPROD_DEPLOY,
    RELEASE_ONLINE_DEPLOY,
    RELEASE_HISTORY_REDEPLOY,
    RELEASE_GRAY_START,
    RELEASE_GRAY_ADJUST,
    RELEASE_GRAY_STOP,
    RELEASE_GRAY_PROMOTE,
    RELEASE_DEPLOYMENT_DETAIL,
    AUTHORING_SESSION_HISTORY,
    AUTHORING_SESSION_CREATE,
    CODING_RUN_STATUS,
    CODING_RUN_CANCEL,
    CODING_CHAT,
    CODING_PATCH_CONFIRM,
    CODING_PATCH_DISCARD;

    /**
     * 根据外部协议中的 method 字符串解析白名单枚举。
     */
    public static Optional<SkillFactoryMethodEnum> of(String code) {
        return Arrays.stream(values())
                .filter(method -> method.name().equals(code))
                .findFirst();
    }
}
