"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import a2flow.a2ui.v1.a2ui_pb2
import abc
import collections.abc
import grpc
import grpc.aio
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_A2uiExecutionDescribeType = typing_extensions.TypeVar(
    '_A2uiExecutionDescribeType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.DescribeRequest,
        a2flow.a2ui.v1.a2ui_pb2.DescribeResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.DescribeRequest,
        a2flow.a2ui.v1.a2ui_pb2.DescribeResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.DescribeRequest,
        a2flow.a2ui.v1.a2ui_pb2.DescribeResponse,
    ],
)

_A2uiExecutionActivateType = typing_extensions.TypeVar(
    '_A2uiExecutionActivateType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.ActivateRequest,
        a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.ActivateRequest,
        a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.ActivateRequest,
        a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
    ],
)

_A2uiExecutionActType = typing_extensions.TypeVar(
    '_A2uiExecutionActType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.ActRequest,
        a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.ActRequest,
        a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.ActRequest,
        a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
    ],
)

class A2uiExecutionStub(typing.Generic[_A2uiExecutionDescribeType, _A2uiExecutionActivateType, _A2uiExecutionActType]):
    @typing.overload
    def __init__(self: A2uiExecutionStub[
        grpc.UnaryUnaryMultiCallable[
            a2flow.a2ui.v1.a2ui_pb2.DescribeRequest,
            a2flow.a2ui.v1.a2ui_pb2.DescribeResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.a2ui.v1.a2ui_pb2.ActivateRequest,
            a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.a2ui.v1.a2ui_pb2.ActRequest,
            a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: A2uiExecutionStub[
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.a2ui.v1.a2ui_pb2.DescribeRequest,
            a2flow.a2ui.v1.a2ui_pb2.DescribeResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.a2ui.v1.a2ui_pb2.ActivateRequest,
            a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.a2ui.v1.a2ui_pb2.ActRequest,
            a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Describe: _A2uiExecutionDescribeType

    Activate: _A2uiExecutionActivateType

    Act: _A2uiExecutionActType

A2uiExecutionAsyncStub: typing_extensions.TypeAlias = A2uiExecutionStub[
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.DescribeRequest,
        a2flow.a2ui.v1.a2ui_pb2.DescribeResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.ActivateRequest,
        a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.a2ui.v1.a2ui_pb2.ActRequest,
        a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse,
    ],
]

class A2uiExecutionServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Describe(
        self,
        request: a2flow.a2ui.v1.a2ui_pb2.DescribeRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.a2ui.v1.a2ui_pb2.DescribeResponse, collections.abc.Awaitable[a2flow.a2ui.v1.a2ui_pb2.DescribeResponse]]: ...

    @abc.abstractmethod
    def Activate(
        self,
        request: a2flow.a2ui.v1.a2ui_pb2.ActivateRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse, collections.abc.Awaitable[a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse]]: ...

    @abc.abstractmethod
    def Act(
        self,
        request: a2flow.a2ui.v1.a2ui_pb2.ActRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse, collections.abc.Awaitable[a2flow.a2ui.v1.a2ui_pb2.RuntimeResponse]]: ...

def add_A2uiExecutionServicer_to_server(servicer: A2uiExecutionServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
