# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from a2flow.a2ui.v1 import a2ui_pb2 as a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in a2flow/a2ui/v1/a2ui_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class A2uiExecutionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
                '/a2flow.a2ui.v1.A2uiExecution/Describe',
                request_serializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.DescribeRequest.SerializeToString,
                response_deserializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.DescribeResponse.FromString,
                _registered_method=True)
        self.Activate = channel.unary_unary(
                '/a2flow.a2ui.v1.A2uiExecution/Activate',
                request_serializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.ActivateRequest.SerializeToString,
                response_deserializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.RuntimeResponse.FromString,
                _registered_method=True)
        self.Act = channel.unary_unary(
                '/a2flow.a2ui.v1.A2uiExecution/Act',
                request_serializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.ActRequest.SerializeToString,
                response_deserializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.RuntimeResponse.FromString,
                _registered_method=True)


class A2uiExecutionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Activate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Act(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A2uiExecutionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.DescribeRequest.FromString,
                    response_serializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.DescribeResponse.SerializeToString,
            ),
            'Activate': grpc.unary_unary_rpc_method_handler(
                    servicer.Activate,
                    request_deserializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.ActivateRequest.FromString,
                    response_serializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.RuntimeResponse.SerializeToString,
            ),
            'Act': grpc.unary_unary_rpc_method_handler(
                    servicer.Act,
                    request_deserializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.ActRequest.FromString,
                    response_serializer=a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.RuntimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2flow.a2ui.v1.A2uiExecution', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2flow.a2ui.v1.A2uiExecution', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class A2uiExecution(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.a2ui.v1.A2uiExecution/Describe',
            a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.DescribeRequest.SerializeToString,
            a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.DescribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Activate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.a2ui.v1.A2uiExecution/Activate',
            a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.ActivateRequest.SerializeToString,
            a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.RuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Act(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2flow.a2ui.v1.A2uiExecution/Act',
            a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.ActRequest.SerializeToString,
            a2flow_dot_a2ui_dot_v1_dot_a2ui__pb2.RuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
