"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import a2flow.capability.v1.capability_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ApplicationRelease(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APP_CODE_FIELD_NUMBER: builtins.int
    SOURCE_ID_FIELD_NUMBER: builtins.int
    DIGEST_FIELD_NUMBER: builtins.int
    APP_BUILD_ID_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    app_code: builtins.str
    source_id: builtins.str
    digest: builtins.str
    app_build_id: builtins.str
    environment: a2flow.capability.v1.capability_pb2.Environment.ValueType
    def __init__(
        self,
        *,
        app_code: builtins.str = ...,
        source_id: builtins.str = ...,
        digest: builtins.str = ...,
        app_build_id: builtins.str = ...,
        environment: a2flow.capability.v1.capability_pb2.Environment.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["app_build_id", b"app_build_id", "app_code", b"app_code", "digest", b"digest", "environment", b"environment", "source_id", b"source_id"]) -> None: ...

Global___ApplicationRelease: typing_extensions.TypeAlias = ApplicationRelease

@typing.final
class RuntimeSession(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    APP_BUILD_ID_FIELD_NUMBER: builtins.int
    PROTOCOL_VERSION_FIELD_NUMBER: builtins.int
    CATALOG_ID_FIELD_NUMBER: builtins.int
    CATALOG_REVISION_FIELD_NUMBER: builtins.int
    CATALOG_DIGEST_FIELD_NUMBER: builtins.int
    token: builtins.str
    app_build_id: builtins.str
    protocol_version: builtins.str
    catalog_id: builtins.str
    catalog_revision: builtins.str
    catalog_digest: builtins.str
    def __init__(
        self,
        *,
        token: builtins.str = ...,
        app_build_id: builtins.str = ...,
        protocol_version: builtins.str = ...,
        catalog_id: builtins.str = ...,
        catalog_revision: builtins.str = ...,
        catalog_digest: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["app_build_id", b"app_build_id", "catalog_digest", b"catalog_digest", "catalog_id", b"catalog_id", "catalog_revision", b"catalog_revision", "protocol_version", b"protocol_version", "token", b"token"]) -> None: ...

Global___RuntimeSession: typing_extensions.TypeAlias = RuntimeSession

@typing.final
class TrustedCard(google.protobuf.message.Message):
    """Only the authenticated Python runtime may populate this from persisted card state."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    RELEASE_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    PARAMS_JSON_FIELD_NUMBER: builtins.int
    SNAPSHOT_JSON_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    revision: builtins.int
    params_json: builtins.bytes
    snapshot_json: builtins.bytes
    @property
    def release(self) -> Global___ApplicationRelease: ...
    @property
    def session(self) -> Global___RuntimeSession: ...
    def __init__(
        self,
        *,
        user_id: builtins.int | None = ...,
        release: Global___ApplicationRelease | None = ...,
        session: Global___RuntimeSession | None = ...,
        revision: builtins.int = ...,
        params_json: builtins.bytes = ...,
        snapshot_json: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_user_id", b"_user_id", "release", b"release", "session", b"session", "user_id", b"user_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_user_id", b"_user_id", "params_json", b"params_json", "release", b"release", "revision", b"revision", "session", b"session", "snapshot_json", b"snapshot_json", "user_id", b"user_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_user_id", b"_user_id"]) -> typing.Literal["user_id"] | None: ...

Global___TrustedCard: typing_extensions.TypeAlias = TrustedCard

@typing.final
class ActivateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    APP_CODE_FIELD_NUMBER: builtins.int
    PARAMS_JSON_FIELD_NUMBER: builtins.int
    EXPECTED_SOURCE_ID_FIELD_NUMBER: builtins.int
    EXPECTED_DIGEST_FIELD_NUMBER: builtins.int
    app_code: builtins.str
    params_json: builtins.bytes
    expected_source_id: builtins.str
    expected_digest: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        app_code: builtins.str = ...,
        params_json: builtins.bytes = ...,
        expected_source_id: builtins.str = ...,
        expected_digest: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["app_code", b"app_code", "context", b"context", "expected_digest", b"expected_digest", "expected_source_id", b"expected_source_id", "params_json", b"params_json"]) -> None: ...

Global___ActivateRequest: typing_extensions.TypeAlias = ActivateRequest

@typing.final
class DescribeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    APP_CODE_FIELD_NUMBER: builtins.int
    app_code: builtins.str
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        app_code: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["app_code", b"app_code", "context", b"context"]) -> None: ...

Global___DescribeRequest: typing_extensions.TypeAlias = DescribeRequest

@typing.final
class CatalogDescriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROTOCOL_VERSION_FIELD_NUMBER: builtins.int
    CATALOG_ID_FIELD_NUMBER: builtins.int
    CATALOG_REVISION_FIELD_NUMBER: builtins.int
    CATALOG_DIGEST_FIELD_NUMBER: builtins.int
    protocol_version: builtins.str
    catalog_id: builtins.str
    catalog_revision: builtins.str
    catalog_digest: builtins.str
    def __init__(
        self,
        *,
        protocol_version: builtins.str = ...,
        catalog_id: builtins.str = ...,
        catalog_revision: builtins.str = ...,
        catalog_digest: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["catalog_digest", b"catalog_digest", "catalog_id", b"catalog_id", "catalog_revision", b"catalog_revision", "protocol_version", b"protocol_version"]) -> None: ...

Global___CatalogDescriptor: typing_extensions.TypeAlias = CatalogDescriptor

@typing.final
class DescribeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RELEASE_FIELD_NUMBER: builtins.int
    PARAMS_SCHEMA_JSON_FIELD_NUMBER: builtins.int
    INTERACTION_MODE_FIELD_NUMBER: builtins.int
    ACTIONS_FIELD_NUMBER: builtins.int
    CATALOG_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    params_schema_json: builtins.bytes
    interaction_mode: builtins.str
    error_code: builtins.str
    @property
    def release(self) -> Global___ApplicationRelease: ...
    @property
    def actions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ActionDescriptor]: ...
    @property
    def catalog(self) -> Global___CatalogDescriptor: ...
    def __init__(
        self,
        *,
        release: Global___ApplicationRelease | None = ...,
        params_schema_json: builtins.bytes = ...,
        interaction_mode: builtins.str = ...,
        actions: collections.abc.Iterable[Global___ActionDescriptor] | None = ...,
        catalog: Global___CatalogDescriptor | None = ...,
        error_code: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["catalog", b"catalog", "release", b"release"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["actions", b"actions", "catalog", b"catalog", "error_code", b"error_code", "interaction_mode", b"interaction_mode", "params_schema_json", b"params_schema_json", "release", b"release"]) -> None: ...

Global___DescribeResponse: typing_extensions.TypeAlias = DescribeResponse

@typing.final
class ActRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    CARD_FIELD_NUMBER: builtins.int
    CORRELATION_ID_FIELD_NUMBER: builtins.int
    RUNTIME_SESSION_TOKEN_FIELD_NUMBER: builtins.int
    APP_BUILD_ID_FIELD_NUMBER: builtins.int
    EXPECTED_SURFACE_REVISION_FIELD_NUMBER: builtins.int
    IDEMPOTENCY_KEY_FIELD_NUMBER: builtins.int
    ACTION_MESSAGE_JSON_FIELD_NUMBER: builtins.int
    correlation_id: builtins.str
    runtime_session_token: builtins.str
    app_build_id: builtins.str
    expected_surface_revision: builtins.int
    idempotency_key: builtins.str
    action_message_json: builtins.bytes
    @property
    def context(self) -> a2flow.capability.v1.capability_pb2.ExecutionContext: ...
    @property
    def card(self) -> Global___TrustedCard: ...
    def __init__(
        self,
        *,
        context: a2flow.capability.v1.capability_pb2.ExecutionContext | None = ...,
        card: Global___TrustedCard | None = ...,
        correlation_id: builtins.str = ...,
        runtime_session_token: builtins.str = ...,
        app_build_id: builtins.str = ...,
        expected_surface_revision: builtins.int = ...,
        idempotency_key: builtins.str = ...,
        action_message_json: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["card", b"card", "context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["action_message_json", b"action_message_json", "app_build_id", b"app_build_id", "card", b"card", "context", b"context", "correlation_id", b"correlation_id", "expected_surface_revision", b"expected_surface_revision", "idempotency_key", b"idempotency_key", "runtime_session_token", b"runtime_session_token"]) -> None: ...

Global___ActRequest: typing_extensions.TypeAlias = ActRequest

@typing.final
class ActionDescriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SURFACE_ID_FIELD_NUMBER: builtins.int
    COMPONENT_ID_FIELD_NUMBER: builtins.int
    ACTION_NAME_FIELD_NUMBER: builtins.int
    CONTEXT_SCHEMA_JSON_FIELD_NUMBER: builtins.int
    surface_id: builtins.str
    component_id: builtins.str
    action_name: builtins.str
    context_schema_json: builtins.bytes
    def __init__(
        self,
        *,
        surface_id: builtins.str = ...,
        component_id: builtins.str = ...,
        action_name: builtins.str = ...,
        context_schema_json: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action_name", b"action_name", "component_id", b"component_id", "context_schema_json", b"context_schema_json", "surface_id", b"surface_id"]) -> None: ...

Global___ActionDescriptor: typing_extensions.TypeAlias = ActionDescriptor

@typing.final
class ExecutionSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINDING_ID_FIELD_NUMBER: builtins.int
    ACTION_CODE_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    CAPABILITY_VERSION_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    binding_id: builtins.str
    action_code: builtins.str
    success: builtins.bool
    capability_version: builtins.int
    error_code: builtins.str
    def __init__(
        self,
        *,
        binding_id: builtins.str = ...,
        action_code: builtins.str = ...,
        success: builtins.bool = ...,
        capability_version: builtins.int = ...,
        error_code: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action_code", b"action_code", "binding_id", b"binding_id", "capability_version", b"capability_version", "error_code", b"error_code", "success", b"success"]) -> None: ...

Global___ExecutionSummary: typing_extensions.TypeAlias = ExecutionSummary

@typing.final
class ActionExecutionObservation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINDING_ID_FIELD_NUMBER: builtins.int
    ACTION_CODE_FIELD_NUMBER: builtins.int
    ARGUMENTS_JSON_FIELD_NUMBER: builtins.int
    RESULT_JSON_FIELD_NUMBER: builtins.int
    CAPABILITY_SUCCESS_FIELD_NUMBER: builtins.int
    BUSINESS_SUCCESS_FIELD_NUMBER: builtins.int
    CAPABILITY_ERROR_CODE_FIELD_NUMBER: builtins.int
    PRESENTATION_ERROR_CODE_FIELD_NUMBER: builtins.int
    binding_id: builtins.str
    action_code: builtins.str
    arguments_json: builtins.bytes
    result_json: builtins.bytes
    capability_success: builtins.bool
    business_success: builtins.bool
    capability_error_code: builtins.str
    presentation_error_code: builtins.str
    def __init__(
        self,
        *,
        binding_id: builtins.str = ...,
        action_code: builtins.str = ...,
        arguments_json: builtins.bytes = ...,
        result_json: builtins.bytes = ...,
        capability_success: builtins.bool = ...,
        business_success: builtins.bool | None = ...,
        capability_error_code: builtins.str = ...,
        presentation_error_code: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_business_success", b"_business_success", "business_success", b"business_success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_business_success", b"_business_success", "action_code", b"action_code", "arguments_json", b"arguments_json", "binding_id", b"binding_id", "business_success", b"business_success", "capability_error_code", b"capability_error_code", "capability_success", b"capability_success", "presentation_error_code", b"presentation_error_code", "result_json", b"result_json"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_business_success", b"_business_success"]) -> typing.Literal["business_success"] | None: ...

Global___ActionExecutionObservation: typing_extensions.TypeAlias = ActionExecutionObservation

@typing.final
class RuntimeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RELEASE_FIELD_NUMBER: builtins.int
    PARAMS_JSON_FIELD_NUMBER: builtins.int
    MESSAGES_JSON_FIELD_NUMBER: builtins.int
    SNAPSHOT_JSON_FIELD_NUMBER: builtins.int
    EXECUTIONS_FIELD_NUMBER: builtins.int
    ACTIONS_FIELD_NUMBER: builtins.int
    COMPLETE_INTERACTION_FIELD_NUMBER: builtins.int
    SELECTED_BRANCH_ID_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    CATALOG_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    INTERACTION_MODE_FIELD_NUMBER: builtins.int
    BUSINESS_SUCCESS_FIELD_NUMBER: builtins.int
    ACTION_OBSERVATION_FIELD_NUMBER: builtins.int
    params_json: builtins.bytes
    messages_json: builtins.bytes
    snapshot_json: builtins.bytes
    complete_interaction: builtins.bool
    selected_branch_id: builtins.str
    error_code: builtins.str
    """RESET_REQUIRED is emitted before capability invocation when publication changes."""
    interaction_mode: builtins.str
    business_success: builtins.bool
    @property
    def release(self) -> Global___ApplicationRelease: ...
    @property
    def executions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ExecutionSummary]: ...
    @property
    def actions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ActionDescriptor]: ...
    @property
    def catalog(self) -> Global___CatalogDescriptor: ...
    @property
    def session(self) -> Global___RuntimeSession: ...
    @property
    def action_observation(self) -> Global___ActionExecutionObservation: ...
    def __init__(
        self,
        *,
        release: Global___ApplicationRelease | None = ...,
        params_json: builtins.bytes = ...,
        messages_json: builtins.bytes = ...,
        snapshot_json: builtins.bytes = ...,
        executions: collections.abc.Iterable[Global___ExecutionSummary] | None = ...,
        actions: collections.abc.Iterable[Global___ActionDescriptor] | None = ...,
        complete_interaction: builtins.bool = ...,
        selected_branch_id: builtins.str = ...,
        error_code: builtins.str = ...,
        catalog: Global___CatalogDescriptor | None = ...,
        session: Global___RuntimeSession | None = ...,
        interaction_mode: builtins.str = ...,
        business_success: builtins.bool = ...,
        action_observation: Global___ActionExecutionObservation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["action_observation", b"action_observation", "catalog", b"catalog", "release", b"release", "session", b"session"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["action_observation", b"action_observation", "actions", b"actions", "business_success", b"business_success", "catalog", b"catalog", "complete_interaction", b"complete_interaction", "error_code", b"error_code", "executions", b"executions", "interaction_mode", b"interaction_mode", "messages_json", b"messages_json", "params_json", b"params_json", "release", b"release", "selected_branch_id", b"selected_branch_id", "session", b"session", "snapshot_json", b"snapshot_json"]) -> None: ...

Global___RuntimeResponse: typing_extensions.TypeAlias = RuntimeResponse
