package dev.a2flow.management.storage.db;

import java.util.Map;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;
import javax.sql.DataSource;

import dev.a2flow.management.storage.db.entity.EntityRelationDO;
import dev.a2flow.management.storage.db.mapper.EntityRelationMapper;
import dev.a2flow.management.access.DatabaseSessionIdentityResolver;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.core.env.MapPropertySource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

/** 独立临时库验证：真实 MyBatis 主键回填及 JDBC/MyBatis 共用事务。 */
public final class ManagementDatabaseConfigurationJdbcTest {
    public static void main(String[] args) throws Exception {
        if (args.length != 2 || !args[0].matches(
                "jdbc:postgresql://127\\.0\\.0\\.1:[0-9]+/workspace_adapter_test")) {
            throw new IllegalArgumentException("Requires isolated workspace_adapter_test database");
        }
        try (AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext()) {
            context.getEnvironment().getPropertySources().addFirst(new MapPropertySource("test", Map.of(
                    "A2FLOW_MANAGEMENT_JDBC_URL", args[0],
                    "A2FLOW_MANAGEMENT_DB_USER", args[1],
                    "A2FLOW_MANAGEMENT_DB_PASSWORD", "isolated-test-only",
                    "A2FLOW_MANAGEMENT_DB_POOL_SIZE", "2")));
            context.register(ManagementDatabaseConfiguration.class, SkillFactoryMapperScanConfig.class);
            context.refresh();
            JdbcTemplate jdbc = new JdbcTemplate(context.getBean(DataSource.class));
            jdbc.execute("""
                    CREATE TABLE entity_relation (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      namespace text, source_entity_type text, source_entity_id text, source_version integer,
                      relation_type text, target_entity_type text, target_entity_id text,
                      target_entity_code text, target_version text, relation_mode text,
                      snapshot_json text, sort_no integer, attribute text, operator text,
                      create_time bigint, update_time bigint)
                    """);
            EntityRelationMapper mapper = context.getBean(EntityRelationMapper.class);
            TransactionTemplate transaction = new TransactionTemplate(context.getBean(PlatformTransactionManager.class));
            EntityRelationDO relation = new EntityRelationDO().setNamespace("isolated")
                    .setSourceEntityType("SKILL").setSourceEntityId("sample").setSourceVersion(1)
                    .setRelationType("USES").setTargetEntityType("APPLICATION").setTargetEntityId("card");
            transaction.executeWithoutResult(status -> {
                if (mapper.insert(relation) != 1 || relation.getId() == null) {
                    throw new AssertionError("PostgreSQL generated key not returned");
                }
                if (jdbc.queryForObject("SELECT count(*) FROM entity_relation", Integer.class) != 1) {
                    throw new AssertionError("JDBC and MyBatis did not share the transaction");
                }
                status.setRollbackOnly();
            });
            if (jdbc.queryForObject("SELECT count(*) FROM entity_relation", Integer.class) != 0) {
                throw new AssertionError("MyBatis write escaped rollback");
            }
            relation.setId(null);
            transaction.executeWithoutResult(status -> mapper.insert(relation));
            if (!"card".equals(mapper.selectById(relation.getId()).getTargetEntityId())) {
                throw new AssertionError("Committed relation did not round trip");
            }
            jdbc.execute("CREATE TABLE users (user_id bigint PRIMARY KEY, role text NOT NULL)");
            jdbc.execute("CREATE TABLE sessions (token_sha256 text PRIMARY KEY, user_id bigint REFERENCES users(user_id), expires_at timestamptz NOT NULL)");
            long userId = Long.MAX_VALUE;
            String token = "a".repeat(43);
            String tokenHash = HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256")
                    .digest(token.getBytes(StandardCharsets.US_ASCII)));
            jdbc.update("INSERT INTO users VALUES (?, 'ADMIN')", userId);
            jdbc.update("INSERT INTO sessions VALUES (?, ?, CURRENT_TIMESTAMP + INTERVAL '1 hour')", tokenHash, userId);
            DatabaseSessionIdentityResolver identities = new DatabaseSessionIdentityResolver(context.getBean(DataSource.class));
            var identity = identities.resolve(token);
            if (identity.userId() != userId || !identity.isAdministrator()) {
                throw new AssertionError("Trusted signed64 identity or role was lost");
            }
            expectDenied(() -> identities.resolve(Long.toString(userId)));
            expectDenied(() -> identities.resolve("b".repeat(43)));
            jdbc.update("UPDATE users SET role = 'USER'");
            if (identities.resolve(token).isAdministrator()) throw new AssertionError("Stale administrator grant");
            jdbc.update("UPDATE users SET role = 'UNKNOWN'");
            expectDenied(() -> identities.resolve(token));
            jdbc.update("UPDATE users SET role = 'ADMIN'");
            jdbc.update("UPDATE sessions SET expires_at = CURRENT_TIMESTAMP - INTERVAL '1 second'");
            expectDenied(() -> identities.resolve(token));
            jdbc.update("DELETE FROM sessions");
            expectDenied(() -> identities.resolve(token));
            System.out.println("PASS: PostgreSQL MyBatis assembly, generated key, shared transaction and rollback");
            System.out.println("PASS: shared account session, exact signed64, role changes, invalid/expired/revoked sessions");
        }
    }

    private static void expectDenied(Runnable request) {
        try {
            request.run();
            throw new AssertionError("Untrusted session accepted");
        } catch (SecurityException expected) {
            // Expected authentication rejection, not a swallowed database error.
        }
    }
}
