"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import a2flow.capability.v1.capability_pb2
import abc
import collections.abc
import grpc
import grpc.aio
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_CapabilityExecutionResolveType = typing_extensions.TypeVar(
    '_CapabilityExecutionResolveType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.capability.v1.capability_pb2.ResolveRequest,
        a2flow.capability.v1.capability_pb2.ResolveResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.capability.v1.capability_pb2.ResolveRequest,
        a2flow.capability.v1.capability_pb2.ResolveResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.capability.v1.capability_pb2.ResolveRequest,
        a2flow.capability.v1.capability_pb2.ResolveResponse,
    ],
)

_CapabilityExecutionExecuteType = typing_extensions.TypeVar(
    '_CapabilityExecutionExecuteType',
    grpc.UnaryUnaryMultiCallable[
        a2flow.capability.v1.capability_pb2.ExecuteRequest,
        a2flow.capability.v1.capability_pb2.ExecuteResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.capability.v1.capability_pb2.ExecuteRequest,
        a2flow.capability.v1.capability_pb2.ExecuteResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        a2flow.capability.v1.capability_pb2.ExecuteRequest,
        a2flow.capability.v1.capability_pb2.ExecuteResponse,
    ],
)

class CapabilityExecutionStub(typing.Generic[_CapabilityExecutionResolveType, _CapabilityExecutionExecuteType]):
    @typing.overload
    def __init__(self: CapabilityExecutionStub[
        grpc.UnaryUnaryMultiCallable[
            a2flow.capability.v1.capability_pb2.ResolveRequest,
            a2flow.capability.v1.capability_pb2.ResolveResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            a2flow.capability.v1.capability_pb2.ExecuteRequest,
            a2flow.capability.v1.capability_pb2.ExecuteResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: CapabilityExecutionStub[
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.capability.v1.capability_pb2.ResolveRequest,
            a2flow.capability.v1.capability_pb2.ResolveResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            a2flow.capability.v1.capability_pb2.ExecuteRequest,
            a2flow.capability.v1.capability_pb2.ExecuteResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Resolve: _CapabilityExecutionResolveType

    Execute: _CapabilityExecutionExecuteType

CapabilityExecutionAsyncStub: typing_extensions.TypeAlias = CapabilityExecutionStub[
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.capability.v1.capability_pb2.ResolveRequest,
        a2flow.capability.v1.capability_pb2.ResolveResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        a2flow.capability.v1.capability_pb2.ExecuteRequest,
        a2flow.capability.v1.capability_pb2.ExecuteResponse,
    ],
]

class CapabilityExecutionServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Resolve(
        self,
        request: a2flow.capability.v1.capability_pb2.ResolveRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.capability.v1.capability_pb2.ResolveResponse, collections.abc.Awaitable[a2flow.capability.v1.capability_pb2.ResolveResponse]]: ...

    @abc.abstractmethod
    def Execute(
        self,
        request: a2flow.capability.v1.capability_pb2.ExecuteRequest,
        context: _ServicerContext,
    ) -> typing.Union[a2flow.capability.v1.capability_pb2.ExecuteResponse, collections.abc.Awaitable[a2flow.capability.v1.capability_pb2.ExecuteResponse]]: ...

def add_CapabilityExecutionServicer_to_server(servicer: CapabilityExecutionServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
