"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Environment:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EnvironmentEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Environment.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ENVIRONMENT_UNSPECIFIED: _Environment.ValueType  # 0
    PRT: _Environment.ValueType  # 1
    ONLINE: _Environment.ValueType  # 2

class Environment(_Environment, metaclass=_EnvironmentEnumTypeWrapper): ...

ENVIRONMENT_UNSPECIFIED: Environment.ValueType  # 0
PRT: Environment.ValueType  # 1
ONLINE: Environment.ValueType  # 2
Global___Environment: typing_extensions.TypeAlias = Environment

@typing.final
class ExecutionContext(google.protobuf.message.Message):
    """Host-only authority. Business/model arguments must never supply or overwrite these fields."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    CLIENT_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    environment: Global___Environment.ValueType
    request_id: builtins.str
    client: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.int | None = ...,
        environment: Global___Environment.ValueType = ...,
        request_id: builtins.str = ...,
        client: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_user_id", b"_user_id", "user_id", b"user_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_user_id", b"_user_id", "client", b"client", "environment", b"environment", "request_id", b"request_id", "user_id", b"user_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_user_id", b"_user_id"]) -> typing.Literal["user_id"] | None: ...

Global___ExecutionContext: typing_extensions.TypeAlias = ExecutionContext

@typing.final
class ResolveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSET_KEY_FIELD_NUMBER: builtins.int
    CONTEXT_FIELD_NUMBER: builtins.int
    asset_key: builtins.str
    @property
    def context(self) -> Global___ExecutionContext: ...
    def __init__(
        self,
        *,
        asset_key: builtins.str = ...,
        context: Global___ExecutionContext | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["asset_key", b"asset_key", "context", b"context"]) -> None: ...

Global___ResolveRequest: typing_extensions.TypeAlias = ResolveRequest

@typing.final
class ResolveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSET_KEY_FIELD_NUMBER: builtins.int
    ACTION_CODE_FIELD_NUMBER: builtins.int
    CAPABILITY_VERSION_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    INPUT_SCHEMA_JSON_FIELD_NUMBER: builtins.int
    KEY_OUTPUT_FIELDS_JSON_FIELD_NUMBER: builtins.int
    RESOLVED_ENVIRONMENT_FIELD_NUMBER: builtins.int
    SOURCE_ID_FIELD_NUMBER: builtins.int
    SOURCE_DIGEST_FIELD_NUMBER: builtins.int
    asset_key: builtins.str
    action_code: builtins.str
    capability_version: builtins.int
    description: builtins.str
    input_schema_json: builtins.str
    key_output_fields_json: builtins.str
    resolved_environment: Global___Environment.ValueType
    source_id: builtins.str
    source_digest: builtins.str
    def __init__(
        self,
        *,
        asset_key: builtins.str = ...,
        action_code: builtins.str = ...,
        capability_version: builtins.int = ...,
        description: builtins.str = ...,
        input_schema_json: builtins.str = ...,
        key_output_fields_json: builtins.str = ...,
        resolved_environment: Global___Environment.ValueType = ...,
        source_id: builtins.str = ...,
        source_digest: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action_code", b"action_code", "asset_key", b"asset_key", "capability_version", b"capability_version", "description", b"description", "input_schema_json", b"input_schema_json", "key_output_fields_json", b"key_output_fields_json", "resolved_environment", b"resolved_environment", "source_digest", b"source_digest", "source_id", b"source_id"]) -> None: ...

Global___ResolveResponse: typing_extensions.TypeAlias = ResolveResponse

@typing.final
class ExecuteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSET_KEY_FIELD_NUMBER: builtins.int
    CONTEXT_FIELD_NUMBER: builtins.int
    ARGUMENTS_JSON_FIELD_NUMBER: builtins.int
    asset_key: builtins.str
    arguments_json: builtins.bytes
    """Raw UTF-8 JSON, not google.protobuf.Struct: exact integers must not pass through double."""
    @property
    def context(self) -> Global___ExecutionContext: ...
    def __init__(
        self,
        *,
        asset_key: builtins.str = ...,
        context: Global___ExecutionContext | None = ...,
        arguments_json: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["arguments_json", b"arguments_json", "asset_key", b"asset_key", "context", b"context"]) -> None: ...

Global___ExecuteRequest: typing_extensions.TypeAlias = ExecuteRequest

@typing.final
class ExecuteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ACTION_CODE_FIELD_NUMBER: builtins.int
    CAPABILITY_VERSION_FIELD_NUMBER: builtins.int
    RESOLVED_ENVIRONMENT_FIELD_NUMBER: builtins.int
    DATA_JSON_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    SOURCE_ID_FIELD_NUMBER: builtins.int
    SOURCE_DIGEST_FIELD_NUMBER: builtins.int
    success: builtins.bool
    action_code: builtins.str
    capability_version: builtins.int
    resolved_environment: Global___Environment.ValueType
    data_json: builtins.bytes
    error_code: builtins.str
    message: builtins.str
    request_id: builtins.str
    source_id: builtins.str
    source_digest: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        action_code: builtins.str = ...,
        capability_version: builtins.int = ...,
        resolved_environment: Global___Environment.ValueType = ...,
        data_json: builtins.bytes = ...,
        error_code: builtins.str = ...,
        message: builtins.str = ...,
        request_id: builtins.str = ...,
        source_id: builtins.str = ...,
        source_digest: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action_code", b"action_code", "capability_version", b"capability_version", "data_json", b"data_json", "error_code", b"error_code", "message", b"message", "request_id", b"request_id", "resolved_environment", b"resolved_environment", "source_digest", b"source_digest", "source_id", b"source_id", "success", b"success"]) -> None: ...

Global___ExecuteResponse: typing_extensions.TypeAlias = ExecuteResponse
