package dev.a2flow.management.model;

/**
 * 业务能力通用执行错误码。
 *
 * <p>上游固定业务能力 Tool 使用该枚举向模型返回稳定失败语义，下游 HTTP Transport 和执行器只选择
 * 最贴近实际失败点的错误码。这里不承载业务接口自身的错误码，也不允许失败后切换目标或降级执行。
 */
public enum CapabilityToolErrorCode {
    TRUSTED_CONTEXT_REQUIRED,
    CAPABILITY_NOT_AUTHORIZED,
    CAPABILITY_RELEASE_NOT_AVAILABLE,
    CAPABILITY_CLIENT_NOT_SUPPORTED,
    CAPABILITY_ACTION_CODE_CONFLICT,
    RELEASE_ENVIRONMENT_REQUIRED,
    RELEASE_ENVIRONMENT_INVALID,
    EXECUTION_PLAN_INVALID,
    ARGUMENT_INVALID,
    ARGUMENT_TYPE_MISMATCH,
    REQUEST_MAPPING_INVALID,
    APPROVAL_REQUIRED,
    AUTHENTICATION_REQUIRED,
    AUTH_MODE_UNSUPPORTED,
    TARGET_REJECTED,
    TRANSPORT_TIMEOUT,
    TRANSPORT_ERROR,
    REDIRECT_REJECTED,
    HTTP_STATUS_REJECTED,
    RESPONSE_TOO_LARGE,
    RESPONSE_JSON_INVALID,
    RESPONSE_SCHEMA_INVALID,
    SOURCE_VERSION_CHANGED
}
