"""Strict adapters for the SW-P1-SUBSET-01 Skill/Policy contract closure."""

from .asset_types import (
    ASSET_KINDS,
    ENVIRONMENTS,
    AssetIdentity,
    AssetKind,
    EffectiveVersions,
    Environment,
    JsonObject,
    JsonScalar,
    JsonValue,
    ReleaseChannel,
    ServingState,
    VersionedAssetIdentity,
)
from .models import (
    CONTRACT_REVISION,
    AuthorizedMaterialHandle,
    ConversationInvocationScope,
    InvocationScope,
    JsonPointerEqualsPolicy,
    ResultInterpretationPolicy,
    ResultInterpretationPolicySet,
    SchemaValidPolicy,
    SkillAssetRef,
    SkillAssetVersionRef,
    TrustedContext,
    TrustedInvocationContext,
    UseSkillArtifact,
    UseSkillContent,
    UseSkillRequest,
    UseSkillResult,
    WorkflowInvocationScope,
    parse_contract_revision,
    parse_definition,
    parse_identifier,
    parse_invocation_scope,
    parse_result_interpretation_policy,
    parse_skill_key,
    validate_definition,
)
from .schema_loader import (
    APPROVED_DEFINITION_NAMES,
    load_approved_schema,
    load_definition_schema,
)
from .validation import ContractValidationError, ValidationIssue
from .user_id import require_user_id, user_id_from_wire, user_id_to_wire

__all__ = [
    "ASSET_KINDS",
    "ENVIRONMENTS",
    "AssetIdentity",
    "AssetKind",
    "EffectiveVersions",
    "Environment",
    "JsonObject",
    "JsonScalar",
    "JsonValue",
    "ReleaseChannel",
    "ServingState",
    "VersionedAssetIdentity",
    "require_user_id",
    "user_id_from_wire",
    "user_id_to_wire",
    "APPROVED_DEFINITION_NAMES",
    "CONTRACT_REVISION",
    "AuthorizedMaterialHandle",
    "ContractValidationError",
    "ConversationInvocationScope",
    "InvocationScope",
    "JsonPointerEqualsPolicy",
    "ResultInterpretationPolicy",
    "ResultInterpretationPolicySet",
    "SchemaValidPolicy",
    "SkillAssetRef",
    "SkillAssetVersionRef",
    "TrustedContext",
    "TrustedInvocationContext",
    "UseSkillArtifact",
    "UseSkillContent",
    "UseSkillRequest",
    "UseSkillResult",
    "ValidationIssue",
    "WorkflowInvocationScope",
    "load_approved_schema",
    "load_definition_schema",
    "parse_contract_revision",
    "parse_definition",
    "parse_identifier",
    "parse_invocation_scope",
    "parse_result_interpretation_policy",
    "parse_skill_key",
    "validate_definition",
]
