-- V001: 新独立管理实例；由 ExplicitManagementMigration 显式执行并登记版本。
-- String/JSON 文本保持 TEXT，与现有 MyBatis StringTypeHandler 一致；时间字段为 epoch 毫秒 BIGINT。
-- 不创建、迁移或复制 users / sessions。所有资产关系继续共用 entity_relation。

CREATE TABLE agent_observation_event (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "observation_id" TEXT,
    "biz_key" TEXT,
    "run_id" TEXT,
    "thread_id" TEXT,
    "conversation_id" TEXT,
    "session_id" TEXT,
    "workspace_id" TEXT,
    "observation_type" TEXT,
    "source" TEXT,
    "idempotency_key" TEXT,
    "summary" TEXT,
    "state_delta_json" TEXT,
    "visible_to_model" INTEGER,
    "operator" TEXT,
    "trace_id" TEXT,
    "attribute" TEXT,
    "deleted" INTEGER NOT NULL DEFAULT 0,
    "create_time" BIGINT,
    "update_time" BIGINT
);

CREATE TABLE skill_asset_release_state (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "asset_type" TEXT,
    "asset_key" TEXT,
    "revision" INTEGER,
    "state_json" TEXT,
    "attribute" TEXT,
    "deleted" INTEGER NOT NULL DEFAULT 0,
    "create_time" BIGINT,
    "update_time" BIGINT
);

CREATE TABLE skill_capability_action_draft (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "draft_id" TEXT,
    "action_code" TEXT,
    "name_cn" TEXT,
    "business_domain" TEXT,
    "technical_owner" TEXT,
    "source_type" TEXT,
    "side_effect_level" TEXT,
    "approval_policy" TEXT,
    "status" TEXT,
    "revision" INTEGER,
    "draft_json" TEXT,
    "validation_json" TEXT,
    "creator" TEXT,
    "modifier" TEXT,
    "deleted" INTEGER NOT NULL DEFAULT 0,
    "create_time" BIGINT,
    "update_time" BIGINT
);

CREATE TABLE entity_relation (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "namespace" TEXT,
    "source_entity_type" TEXT,
    "source_entity_id" TEXT,
    "source_version" INTEGER,
    "relation_type" TEXT,
    "target_entity_type" TEXT,
    "target_entity_id" TEXT,
    "target_entity_code" TEXT,
    "target_version" TEXT,
    "relation_mode" TEXT,
    "snapshot_json" TEXT,
    "sort_no" INTEGER,
    "attribute" TEXT,
    "operator" TEXT,
    "create_time" BIGINT,
    "update_time" BIGINT
);

CREATE TABLE skill_asset_principal (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "namespace" TEXT,
    "asset_type" TEXT,
    "asset_key" TEXT,
    "principal_type" TEXT,
    "principal_id" TEXT,
    "role_type" TEXT,
    "status" TEXT,
    "attribute" TEXT,
    "creator" TEXT,
    "modifier" TEXT,
    "create_time" BIGINT,
    "update_time" BIGINT
);

CREATE TABLE skill_factory_authoring_event (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "record_id" TEXT,
    "session_id" TEXT,
    "schema_version" TEXT,
    "event_type" TEXT,
    "event_id" TEXT,
    "block_id" TEXT,
    "source" TEXT,
    "workspace_id" TEXT,
    "invoke_id" TEXT,
    "message_id" TEXT,
    "run_id" TEXT,
    "conversation_id" TEXT,
    "thread_id" TEXT,
    "trace_id" TEXT,
    "model_content_block_json" TEXT,
    "payload_type" TEXT,
    "payload_json" TEXT,
    "content" TEXT,
    "tool_call_id" TEXT,
    "tool_name" TEXT,
    "tool_args" TEXT,
    "tool_success" INTEGER,
    "token_count" BIGINT,
    "enter_token_count" BIGINT,
    "output_token_count" BIGINT,
    "has_knowledge" INTEGER,
    "timestamp" BIGINT,
    "answer_agent_id" BIGINT,
    "attribute" TEXT,
    "deleted" INTEGER NOT NULL DEFAULT 0,
    "create_time" BIGINT,
    "update_time" BIGINT
);

CREATE TABLE skill_factory_authoring_session (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "session_id" TEXT,
    "biz_key" TEXT,
    "scope_type" TEXT,
    "scope_id" TEXT,
    "workspace_id" TEXT,
    "title" TEXT,
    "creator" TEXT,
    "last_operator" TEXT,
    "active" INTEGER,
    "message_count" BIGINT,
    "last_message_time" BIGINT,
    "attribute" TEXT,
    "deleted" INTEGER NOT NULL DEFAULT 0,
    "create_time" BIGINT,
    "update_time" BIGINT
);

CREATE TABLE skill_factory_authoring_turn (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "turn_id" TEXT,
    "session_id" TEXT,
    "role" TEXT,
    "message_id" TEXT,
    "text" TEXT,
    "operator" TEXT,
    "timestamp" BIGINT,
    "attribute" TEXT,
    "deleted" INTEGER NOT NULL DEFAULT 0,
    "create_time" BIGINT,
    "update_time" BIGINT
);

CREATE TABLE skill_component_registry (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "asset_type" TEXT,
    "component_name" TEXT,
    "component_name_cn" TEXT,
    "a2ui_component_type" TEXT,
    "a2ui_contract_json" TEXT,
    "dsl_type" TEXT,
    "agent_ui_dsl" TEXT,
    "protocol_version" INTEGER,
    "interaction_mode" TEXT,
    "bundle_url" TEXT,
    "app_bundle_url" TEXT,
    "owner" TEXT,
    "scene" TEXT,
    "params_schema_json" TEXT,
    "render_template_json" TEXT,
    "official_demo_json" TEXT,
    "message_demo_json" TEXT,
    "integration_prompt" TEXT,
    "allowed_actions_json" TEXT,
    "runtime_config_json" TEXT,
    "support_clients" TEXT,
    "enabled" INTEGER,
    "attribute" TEXT,
    "operator" TEXT,
    "create_time" BIGINT,
    "update_time" BIGINT
);

CREATE TABLE skill_draft (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "skill_code" TEXT,
    "skill_name_cn" TEXT,
    "skill_name_en" TEXT,
    "skill_description" TEXT,
    "business_domain" TEXT,
    "capability_domain" TEXT,
    "create_source" TEXT,
    "workspace_id" TEXT,
    "workspace_path" TEXT,
    "file_tree_digest" TEXT,
    "source_zip_url" TEXT,
    "version" INTEGER,
    "lang_bridge_skill_id" BIGINT,
    "status" TEXT,
    "owner" TEXT,
    "creator" TEXT,
    "modifier" TEXT,
    "ext_json" TEXT,
    "attribute" TEXT,
    "deleted" INTEGER NOT NULL DEFAULT 0,
    "create_time" BIGINT,
    "update_time" BIGINT
);

CREATE TABLE workflow_definition (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "workflow_code" TEXT,
    "specialist_code" TEXT,
    "display_name" TEXT,
    "description" TEXT,
    "draft_contract_version" INTEGER,
    "draft_revision" BIGINT,
    "draft_digest" TEXT,
    "draft_payload_json" TEXT,
    "attribute_json" TEXT,
    "created_by" TEXT,
    "updated_by" TEXT,
    "deleted" INTEGER NOT NULL DEFAULT 0,
    "create_time" BIGINT,
    "update_time" BIGINT
);

CREATE UNIQUE INDEX skill_draft_code_live_uq ON skill_draft (skill_code) WHERE deleted = 0;
CREATE UNIQUE INDEX skill_draft_workspace_live_uq ON skill_draft (workspace_id) WHERE deleted = 0;
CREATE INDEX skill_draft_updated_idx ON skill_draft (update_time DESC, id DESC) WHERE deleted = 0;
CREATE UNIQUE INDEX capability_draft_id_live_uq ON skill_capability_action_draft (draft_id) WHERE deleted = 0;
CREATE INDEX capability_action_live_idx ON skill_capability_action_draft (action_code) WHERE deleted = 0;
CREATE UNIQUE INDEX component_identity_uq ON skill_component_registry (asset_type, component_name);
CREATE INDEX component_business_dsl_idx ON skill_component_registry (dsl_type, agent_ui_dsl);
CREATE UNIQUE INDEX workflow_code_live_uq ON workflow_definition (workflow_code) WHERE deleted = 0;
CREATE INDEX workflow_updated_live_idx ON workflow_definition (update_time DESC, id DESC) WHERE deleted = 0;
CREATE INDEX workflow_specialist_live_idx ON workflow_definition (specialist_code, update_time DESC, id DESC) WHERE deleted = 0;
CREATE UNIQUE INDEX release_identity_uq ON skill_asset_release_state (asset_type, asset_key);
CREATE UNIQUE INDEX principal_identity_uq ON skill_asset_principal
    (namespace, asset_type, asset_key, principal_type, principal_id, role_type);
CREATE INDEX principal_active_owner_idx ON skill_asset_principal (namespace, asset_type, asset_key, status, role_type);
CREATE INDEX relation_source_idx ON entity_relation
    (namespace, source_entity_type, source_entity_id, source_version, relation_type, sort_no);
CREATE INDEX relation_target_idx ON entity_relation (namespace, target_entity_type, target_entity_id);
CREATE UNIQUE INDEX authoring_session_identity_uq ON skill_factory_authoring_session (session_id);
CREATE INDEX authoring_session_scope_idx ON skill_factory_authoring_session
    (biz_key, scope_type, scope_id, active, update_time DESC) WHERE deleted = 0;
CREATE UNIQUE INDEX authoring_turn_identity_uq ON skill_factory_authoring_turn (turn_id);
CREATE INDEX authoring_turn_session_idx ON skill_factory_authoring_turn (session_id, timestamp, id) WHERE deleted = 0;
CREATE UNIQUE INDEX authoring_event_identity_uq ON skill_factory_authoring_event (record_id);
CREATE INDEX authoring_event_session_idx ON skill_factory_authoring_event (session_id, timestamp, id) WHERE deleted = 0;
CREATE UNIQUE INDEX observation_identity_uq ON agent_observation_event (observation_id);
CREATE UNIQUE INDEX observation_dedupe_uq ON agent_observation_event (biz_key, thread_id, source, idempotency_key)
    WHERE deleted = 0 AND idempotency_key IS NOT NULL AND idempotency_key <> '';
CREATE INDEX observation_thread_idx ON agent_observation_event (biz_key, thread_id, id DESC) WHERE deleted = 0;

-- 复用现有共享资产表协议；namespace 区分工作区文档、普通资产和不可变构建包。
CREATE TABLE a2flow_management_drafts (
    namespace TEXT NOT NULL,
    kind TEXT NOT NULL,
    asset_key TEXT NOT NULL,
    revision BIGINT NOT NULL,
    document BYTEA NOT NULL,
    digest TEXT NOT NULL,
    updated_by BIGINT NOT NULL,
    PRIMARY KEY (namespace, kind, asset_key)
);
CREATE TABLE a2flow_asset_versions (
    namespace TEXT NOT NULL,
    kind TEXT NOT NULL,
    asset_key TEXT NOT NULL,
    version_id TEXT NOT NULL,
    document BYTEA NOT NULL,
    digest TEXT NOT NULL,
    PRIMARY KEY (namespace, kind, asset_key, version_id)
);
